local splits = require('smart-splits')
splits.setup()
vim.keymap.set('n', '<M-H>', splits.resize_left)
vim.keymap.set('n', '<M-J>', splits.resize_down)
vim.keymap.set('n', '<M-K>', splits.resize_up)
vim.keymap.set('n', '<M-L>', splits.resize_right)
vim.keymap.set('n', '<M-h>', splits.move_cursor_left)
vim.keymap.set('n', '<M-j>', splits.move_cursor_down)
vim.keymap.set('n', '<M-k>', splits.move_cursor_up)
vim.keymap.set('n', '<M-l>', splits.move_cursor_right)
vim.keymap.set('n', '<M-p>', splits.move_cursor_previous)
