vim.keymap.set('n', '<Leader>gg', '<Cmd>G<CR>')
vim.keymap.set('n', '<Leader>gP', '<Cmd>G push<CR>')
vim.keymap.set('n', '<Leader>gp', '<Cmd>G pull<CR>')
vim.keymap.set('n', '<Leader>gl', '<Cmd>G log %<CR>')
vim.keymap.set('n', '<Leader>gL', '<Cmd>G log<CR>')
